version: '3.4'

services:

  rabbitmq:
    image: rabbitmq:3-management-alpine

  redis:
    image: redis:alpine

  seq:
    image: datalust/seq:latest

  sqldata:
    image: mcr.microsoft.com/mssql/server:2017-latest 

  zipkin:
    image: openzipkin/zipkin-slim

  basket-api:
    image: ${REGISTRY:-eshop}/basket.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Basket/Basket.API/Dockerfile
    depends_on:
      - identity-api
      - redis

  basket-api-dapr:
    image: "daprio/daprd:1.0.0"
    network_mode: "service:basket-api"
    depends_on:
      - basket-api

  catalog-api:
    image: ${REGISTRY:-eshop}/catalog.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Catalog/Catalog.API/Dockerfile
    depends_on:
      - sqldata

  catalog-api-dapr:
    image: "daprio/daprd:1.0.0"
    network_mode: "service:catalog-api"
    depends_on:
      - catalog-api

  identity-api:
    image: ${REGISTRY:-eshop}/identity.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Identity/Identity.API/Dockerfile
    depends_on:
      - sqldata

  ordering-api:
    image: ${REGISTRY:-eshop}/ordering.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Ordering/Ordering.API/Dockerfile
    depends_on:
      - sqldata

  ordering-api-dapr:
    image: "daprio/daprd:1.0.0"
    network_mode: "service:ordering-api"
    depends_on:
      - ordering-api

  payment-api:
    image: ${REGISTRY:-eshop}/payment.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Payment/Payment.API/Dockerfile

  payment-api-dapr:
    image: "daprio/daprd:1.0.0"
    network_mode: "service:payment-api"
    depends_on:
      - payment-api

  webshoppingagg:
    image: ${REGISTRY:-eshop}/webshoppingagg:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/ApiGateways/Aggregators/Web.Shopping.HttpAggregator/Dockerfile
    depends_on:
      - basket-api
      - catalog-api
      - identity-api
      - ordering-api
      - sqldata

  webshoppingagg-dapr:
    image: "daprio/daprd:1.0.0"
    network_mode: "service:webshoppingagg"
    depends_on:
      - webshoppingagg

  webshoppingapigw:
    image: envoyproxy/envoy:v1.14.2

  webshoppingapigw-dapr:
    image: "daprio/daprd:1.0.0"
    network_mode: "service:webshoppingapigw"
    depends_on:
      - webshoppingapigw

  webspa:
    image: ${REGISTRY:-eshop}/webspa:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/Web/WebSPA/Dockerfile
    depends_on:
      - webshoppingagg

  webstatus:
    image: ${REGISTRY:-eshop}/webstatus:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/Web/WebStatus/Dockerfile

  dapr-placement:
    image: "daprio/dapr:1.0.0"