version: '3.4'

# The default docker-compose.override file can use the "localhost" as the external name for testing web apps within the same dev machine.
# The ESHOP_EXTERNAL_DNS_NAME_OR_IP environment variable is taken, by default, from the ".env" file defined like:
#     ESHOP_EXTERNAL_DNS_NAME_OR_IP=localhost
# but values present in the environment vars at runtime will always override those defined inside the .env file

services:

  maildev:
    ports:
      - "5500:80"

  rabbitmq:
    ports:
      - "5672:5672"

  redis:
    image: redis:alpine
    ports:
      - "5379:6379"

  seq:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5340:80"

  sqldata:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"
    volumes:
      - eshop-sqldata:/var/opt/mssql

  zipkin:
    ports:
      - "5411:9411"

  basket-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - IdentityUrl=http://identity-api
      - IdentityUrlExternal=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5105
      - SeqServerUrl=http://seq
    ports:
      - "5103:80"
      - "50001:50001"

  basket-api-dapr:
    command: ["./daprd",
      "-app-id", "basket-api",
      "-app-port", "80",
      "-components-path", "/components",
      "-config", "/configuration/eshop-config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  blazor-client:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ApiGatewayUrlExternal=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5202
      - IdentityUrlExternal=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5105
      - SeqServerUrl=http://seq
    ports:
      - "5104:80"

  catalog-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - RetryMigrations=true
      - SeqServerUrl=http://seq
      # Temporarily while waiting for https://github.com/dapr/dotnet-sdk/issues/779 to get fixed.
      - ConnectionStrings__CatalogDB=Server=sqldata;Database=Microsoft.eShopOnDapr.Services.CatalogDb;User Id=sa;Password=Pass@word;TrustServerCertificate=true
    ports:
      - "5101:80"
      - "50002:50001"

  catalog-api-dapr:
    command: ["./daprd",
      "-app-id", "catalog-api",
      "-app-port", "80",
      "-components-path", "/components",
      "-config", "/configuration/eshop-config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  identity-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - SeqServerUrl=http://seq
      - RetryMigrations=true
      - IssuerUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5105
      - BlazorClientUrlExternal=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5104
      - BasketApiUrlExternal=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5103
      - OrderingApiUrlExternal=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5102
      - ShoppingAggregatorApiUrlExternal=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5121
      # Temporarily while waiting for https://github.com/dapr/dotnet-sdk/issues/779 to get fixed.
      - ConnectionStrings__IdentityDB=Server=sqldata;Database=Microsoft.eShopOnDapr.Service.IdentityDb;User Id=sa;Password=Pass@word;TrustServerCertificate=true
    ports:
      - "5105:80"
      - "50009:50001"

  identity-api-dapr:
    command: ["./daprd",
      "-app-id", "identity-api",
      "-app-port", "80",
      "-placement-host-address", "dapr-placement:50000",
      "-components-path", "/components",
      "-config", "/configuration/eshop-config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  ordering-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - IdentityUrl=http://identity-api
      - IdentityUrlExternal=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5105
      - RetryMigrations=true
      - SeqServerUrl=http://seq
      # Temporarily while waiting for https://github.com/dapr/dotnet-sdk/issues/779 to get fixed.
      - ConnectionStrings__OrderingDB=Server=sqldata;Database=Microsoft.eShopOnDapr.Services.OrderingDb;User Id=sa;Password=Pass@word;TrustServerCertificate=true
    ports:
      - "5102:80"
      - "50003:50001"

  ordering-api-dapr:
    command: ["./daprd",
      "-app-id", "ordering-api",
      "-app-port", "80",
      "-log-level", "debug",
      "-placement-host-address", "dapr-placement:50000",
      "-components-path", "/components",
      "-config", "/configuration/eshop-config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  payment-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - SeqServerUrl=http://seq
    ports:
      - "5108:80"
      - "50006:50001"

  payment-api-dapr:
    command: ["./daprd",
      "-app-id", "payment-api",
      "-app-port", "80",
      "-components-path", "/components",
      "-config", "/configuration/eshop-config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  webshoppingagg:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityUrl=http://identity-api
      - IdentityUrlExternal=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5105
      - SeqServerUrl=http://seq
      - BasketUrlHC=http://basket-api/hc
      - CatalogUrlHC=http://catalog-api/hc
      - IdentityUrlHC=http://identity-api/hc
    ports:
      - "5121:80"
      - "50007:50001"

  webshoppingagg-dapr:
    command: ["./daprd",
      "-app-id", "webshoppingagg",
      "-app-port", "80",
      "-components-path", "/components",
      "-config", "/configuration/eshop-config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  webshoppingapigw:
    environment:
      - ENVOY_CATALOG_API_ADDRESS=catalog-api
      - ENVOY_CATALOG_API_PORT=80
      - ENVOY_ORDERING_API_ADDRESS=ordering-api
      - ENVOY_ORDERING_API_PORT=80
    ports:
      - "5202:80"
      - "15202:8001"
      - "50008:50001"

  webshoppingapigw-dapr:
    command: ["./daprd",
      "-app-id", "webshoppingapigw",
      "-app-port", "80",
      "-components-path", "/components",
      "-config", "/configuration/eshop-config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  webstatus:
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - HealthChecksUI__HealthChecks__0__Name=Basket API
      - HealthChecksUI__HealthChecks__0__Uri=http://basket-api/hc
      - HealthChecksUI__HealthChecks__1__Name=Catalog API
      - HealthChecksUI__HealthChecks__1__Uri=http://catalog-api/hc
      - HealthChecksUI__HealthChecks__2__Name=Identity API
      - HealthChecksUI__HealthChecks__2__Uri=http://identity-api/hc
      - HealthChecksUI__HealthChecks__3__Name=Ordering API
      - HealthChecksUI__HealthChecks__3__Uri=http://ordering-api/hc
      - HealthChecksUI__HealthChecks__4__Name=Payment API
      - HealthChecksUI__HealthChecks__4__Uri=http://payment-api/hc
      - HealthChecksUI__HealthChecks__5__Name=Web Shopping Aggregator
      - HealthChecksUI__HealthChecks__5__Uri=http://webshoppingagg/hc
      - HealthChecksUI__HealthChecks__6__Name=Blazor UI Host
      - HealthChecksUI__HealthChecks__6__Uri=http://blazor-client/hc
    ports:
      - "5107:80"

  dapr-placement:
    command: ["./placement", "-port", "50000", "-log-level", "debug"]
    ports:
      - "50000:50000"

volumes:
  eshop-sqldata:
    external: false
  eshop-nosqldata:
    external: false
  eshop-basketdata:
    external: false

