version: '3.4'

services:
  maildev-test:
    ports:
      - "5500:1080"
      - "1025:1025"

  rabbitmq-test:
    ports:
      - "5672:5672"

  redis-test:
    ports:
      - "5379:6379"

  sqldata-test:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"

  integration-test:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_BASKET_URLS=http://0.0.0.0:81
      - ASPNETCORE_BASKET_DAPR_HTTP_ENDPOINT=http://127.0.0.1:3501
      - ASPNETCORE_BASKET_DAPR_GRPC_ENDPOINT=http://127.0.0.1:50002
      - ASPNETCORE_ORDERING_URLS=http://0.0.0.0:82
      - ASPNETCORE_ORDERING_DAPR_HTTP_ENDPOINT=http://127.0.0.1:3502
      - ASPNETCORE_ORDERING_DAPR_GRPC_ENDPOINT=http://127.0.0.1:50003
      - SeqServerUrl=http://seq-test
      - RetryMigrations=true
      - IssuerUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5105
      - BlazorClientUrlExternal=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5104
      - BasketApiUrlExternal=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5103
      - OrderingApiUrlExternal=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5102
      - ShoppingAggregatorApiUrlExternal=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5121
      - IdentityUrl=http://identity-api-test
      - Serilog__MinimumLevel__Override__Microsoft=Information
    entrypoint:
        - dotnet
        - test
        - --logger
        - trx;LogFileName=/tests/integration-test-results.xml

  basket-api-dapr-integration-test:
    command: ["./daprd",
      "-app-id", "basket-api-test",
      "-app-port", "81",
      "-dapr-http-port", "3501",
      "-dapr-grpc-port", "50002",
      "-metrics-port", "9091",
      "-log-level", "debug",
      "--enable-api-logging",
      "-components-path", "/components",
      "-config", "/configuration/eshop-config.yaml"
      ]
    volumes:
      - "./dapr/components-test/:/components"
      - "./dapr/configuration/:/configuration"

  ordering-api-dapr-integration-test:
    command: ["./daprd",
      "-app-id", "ordering-api-test",
      "-app-port", "82",
      "-dapr-http-port", "3502",
      "-dapr-grpc-port", "50003",
      "-metrics-port", "9092",
      "-log-level", "debug",
      "--enable-api-logging",
      "-placement-host-address", "dapr-placement-test:50000",
      "-components-path", "/components",
      "-config", "/configuration/eshop-config.yaml"
      ]
    volumes:
      - "./dapr/components-test/:/components"
      - "./dapr/configuration/:/configuration"

  dapr-placement-test:
    command: ["./placement", "-port", "50000", "-log-level", "debug"]
    ports:
      - "50000:50000"