global using HealthChecks.UI.Client;
global using Microsoft.AspNetCore;
global using Microsoft.AspNetCore.Diagnostics.HealthChecks;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Mvc.RazorPages;
global using Microsoft.eShopOnDapr.BlazorClient.Host;
global using Microsoft.Extensions.Diagnostics.HealthChecks;
global using Microsoft.Extensions.Options;
global using System.Diagnostics;
