global using System.Security.Claims;
global using System.Text;
global using System.Text.Json;
global using Dapr.Client;
global using FunctionalTests.Extensions;
global using FunctionalTests.Middlewares;
global using FunctionalTests.Services.Basket;
global using FunctionalTests.Services.Ordering;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.AspNetCore.Hosting;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc.Testing;
global using Microsoft.AspNetCore.TestHost;
global using Microsoft.eShopOnDapr.BlazorClient.Ordering;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Xunit;
global using static FunctionalTests.Services.Basket.BasketWebApplicationFactory;
global using static FunctionalTests.Services.Ordering.OrderingWebApplicationFactory;